### ISSUE TITLE
EC2 Health checks might not be configured correctly

### ISSUE THREAD

**Issue by EthanTang-Zq** [awsdocs/aws-global-accelerator-dev-guide#13]
May I ask how to solve it? Listeners in this accelerator have an unhealthy status. To make sure that Global Accelerator can run health checks successfully, ensure that a service is responding on the protocol and port that you specified in the health check configuration.Learn more

**Comment by staciasnapp** [comment]
Hi tangzhiqiangh, how you verify that the protocol and port can respond to the service will depend on your specific configuration. May I suggest that you engage with a forum group or AWS support for assistance with your setup? If you have suggestions or concerns for how we could address this better in the docs, please feel free to provide feedback on the docs page!

Thanks!
