### ISSUE TITLE
Does Global Accelerator Listener supports both TCP and UDP protocols?

### ISSUE THREAD

**Issue by andycui66** [awsdocs/aws-global-accelerator-dev-guide#14]
https://github.com/awsdocs/aws-global-accelerator-dev-guide/blob/main/doc_source/about-listeners.md

The doc says it supports both protocols but on AWS console I do not see the option.
![Screen Shot 2022-08-22 at 6 15 22 PM](https://user-images.githubusercontent.com/5249524/186028183-62b78168-c12a-4cfc-a01e-fca3952d09d3.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
